spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.64:3306/user?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root

  main:
    allow-bean-definition-overriding: true #如果有相同的Bean，会覆盖
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update # 如果实体类对应表不存在，就自动创建表。
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # 数据库方言
        format_sql: true # 格式化SQL语句
    show-sql: true # 打印SQL语句